[book]
authors = ["Aldrin Montana"]
multilingual = false
src = "consistency-dps-content"
title = "Consistency Types in Declarative Programmable Storage"

[build]
build-dir = "/srv/http/consistency-types-dps"

[output.html]
mathjax-support = true
