[book]
authors = ["Aldrin Montana"]
multilingual = false
src = "book-content"
title = "Mixing Consistency in Declarative Programmable Storage"

[build]
build-dir = "/srv/http/mixing-consistency"

[output.html]
mathjax-support = true
